---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: simple-nginx
  template:
    metadata:
      labels:
        app: simple-nginx
    spec:
      containers:
      - image: registry.access.redhat.com/ubi8/nginx-120:1-60
        name: nginx
        command:
          - /bin/sh
          - -c
          - |

            set -x

            echo "Hello from MicroShift at the Edge" >> /opt/app-root/src/index.html

            nginx -g "daemon off;"
  triggers:
  - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: simple-nginx
  name: simple-nginx
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: simple-nginx
  sessionAffinity: None
  type: ClusterIP
